CREATE TABLE IF NOT EXISTS "House" (
    "id" SERIAL PRIMARY KEY,
    "address" VARCHAR(255) NOT NULL,
    "price" FLOAT,
    "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);